### ISSUE TITLE
[meta] Open PRs

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/crankshaft#194]
### Docs updates
- [ ] https://github.com/CartoDB/crankshaft/pull/193 Minor docs updates to code snippets (no code touched)
- [ ] https://github.com/CartoDB/crankshaft/pull/179 Notes about outputs of moran's i
- [ ] https://github.com/CartoDB/crankshaft/pull/155 Notes about how to use the PL/Python functions which have queries as arguments

#### Needs code review (not ready to go)
- [ ] https://github.com/CartoDB/crankshaft/pull/175 Spatial lag as an analysis (needs code review)
- [ ] https://github.com/CartoDB/crankshaft/pull/147 Should be ready to go

#### Status uncertain
- [ ] https://github.com/CartoDB/crankshaft/pull/148

### Refactoring / bug fixes
- [ ] https://github.com/CartoDB/crankshaft/pull/171 Segmentation refactoring
- [ ] https://github.com/CartoDB/crankshaft/pull/165 Adds better geometry support to PIA
- [ ] https://github.com/CartoDB/crankshaft/pull/157 Better errors for older spatial stats functions
- [ ] https://github.com/CartoDB/crankshaft/pull/150 Refactors nonspatial kmeans to more consistent internals as compared to other functions

## Incomplete

- [ ] https://github.com/CartoDB/crankshaft/pull/136 weighted median center
- [ ] https://github.com/CartoDB/crankshaft/pull/14 Union adjacent
- [ ] https://github.com/CartoDB/crankshaft/pull/160 Max-p
