### ISSUE TITLE
Data Observatory API functions [Meta Issue]

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/crankshaft#24]
Documented in PostGIS format

- [ ] OBS_GetDemographicSnapshot
- [ ] OBS_GetGeometry
- [ ] OBS_GetGeometryId
- [ ] OBS_Get_Population
- [ ] OBS_Augment_Census
- [ ] OBS_Aggregate_Census (Andy)
- [ ] OBS_GetThematicGroupbyTag
- [ ] OBS_GetSegmentationSnapshot
- [ ] OBS_SegmentCustomers
- [ ] OBS_MarketPotential
- [ ] OBS_Search
- [ ] OBS_Theme_Tags
- [ ] OBS_Theme_Info
- [ ] OBS_Get_Available_Geometries
- [ ] CDB_AreasOfInterest
- [ ] CDB_PredictTrend
- [ ] CDB_PredictNextValue

Pull request to Crankshaft

- [x] OBS_GetDemographicSnapshot
- [x] OBS_GetGeometry
- [ ] OBS_GetGeometryId
- [ ] OBS_Get_Population
- [x] OBS_Augment_Census
- [ ] ~~OBS_Aggregate_Census~~
- [x] OBS_GetThematicGroupbyTag
- [x] OBS_GetSegmentationSnapshot
- [ ] OBS_SegmentCustomers
- [ ] OBS_MarketPotential
- [x] OBS_Search
- [ ] OBS_Theme_Tags
- [ ] OBS_Theme_Info
- [x] OBS_Get_Available_Geometries
- [x] CDB_AreasOfInterest
    * CDB_AreasOfInterest_Local
    * CDB_AreasOfInterest_Global
    * CDB_AreasOfInterest_Local_Rate
    * CDB_AreasOfInterest_Global_Rate
- [ ] CDB_PredictTrend
- [ ] CDB_PredictNextValue

@ohasselblad @stuartlynn @talos i wanted to start tracking the progress of these API methods. a meta issue is good enough for me. we should start trying to check these off pretty fast. The naming isn't final, so if you want to tweak it great. Pick which is your standard when to underscore "_" and when to camel case "AnG" and do it. Leave comments or update me here too, https://docs.google.com/document/d/1aidAJJU_m_ueFNT_w6hpJLDdN7ubRD_gqF6G4-fePKA/edit# if yuo want to discuss any of the particular methods, let's get going. The first one we need asap that Stuart and John have already started on is the first, OBS_GetDemographicSnapshot

**Comment by andrewxhill** [comment]
@stuartlynn @talos the two critical ones coming from javier are these,

- OBS_GetDemographicSnapshot
- OBS_GetSegmentationSnapshot

Today you two are working on OBS_GetDemographicSnapshot. As soon as we have that in a good state let me know, I need to run through a test of deployment with Rafa (basically ensuring that we can enable quotas etc).

Tomorrow can you start sprinting on the segmentation one? First, try to define a handful of interesting segments that we could develop layers for (i know there was the idea of house buying millenials or things like that). Take a look at the ESRI ones for inspiration. Second, let's start creating the layers and working on integrating in the ETL.

**Comment by ohasselblad** [comment]
`CDB_AreasOfInterest` functions are ready to ship: #19! Working on completing docs now.

**Comment by stuartlynn** [comment]
@andrewxhill  So we have working version of both OBS_GetDemographicSnapshot and OBS_GetSegmentationSnapshot with a single segment in the OBS_GetSegmentationSnapshot function but with a clear path to be able to add more. 

Need to clarify where this will live for now but currently we are just copying and pasting a bunch of functions in to the editor works.

**Comment by javisantana** [comment]
hey, depending on how we plan to do the DO services this might be placed in a different repo, @rafatower will give you more details

**Comment by andrewxhill** [comment]
closing this in favor of a more stable set of functions https://github.com/CartoDB/observatory-extension/issues/15
